### ISSUE TITLE
License type.

### ISSUE THREAD

**Issue by nuket** [beatgammit/dpm#1]
Hi, was just thinking about trying to create something like this myself. I think it would definitely help the adoption of D. So I'd like to help out however I can in getting this off the ground. Out of curiosity, what license were you thinking about using? Something like the BSD 3-clause?

**Comment by beatgammit** [comment]
@nuket If you're still interested, BSD 3-clause suits me fine. I can throw it in the repo if you're interested.

I'm no longer interested in this project. Sorry I missed this issue.
